// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbqLSHxF4Mo9EpcZSMSyBoy2tojMgB8Tw',
    appId: '1:104432287034:web:bf3ecfb40b9b87c674a403',
    messagingSenderId: '104432287034',
    projectId: 'trackify-f887d',
    authDomain: 'trackify-f887d.firebaseapp.com',
    storageBucket: 'trackify-f887d.appspot.com',
    measurementId: 'G-CK5JLGD3Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD9iqQVM48--ZXMhW0tZBKXDJgkqcYAjA',
    appId: '1:104432287034:android:cf97c1221ff2483a74a403',
    messagingSenderId: '104432287034',
    projectId: 'trackify-f887d',
    storageBucket: 'trackify-f887d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZSJSw8R0x8QmJGKXNYzgvFWZtifYGX4k',
    appId: '1:104432287034:ios:5a1266817b160b1674a403',
    messagingSenderId: '104432287034',
    projectId: 'trackify-f887d',
    storageBucket: 'trackify-f887d.appspot.com',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZSJSw8R0x8QmJGKXNYzgvFWZtifYGX4k',
    appId: '1:104432287034:ios:5a1266817b160b1674a403',
    messagingSenderId: '104432287034',
    projectId: 'trackify-f887d',
    storageBucket: 'trackify-f887d.appspot.com',
    iosBundleId: 'com.example.trackify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbqLSHxF4Mo9EpcZSMSyBoy2tojMgB8Tw',
    appId: '1:104432287034:web:d041fca8f5f7cecc74a403',
    messagingSenderId: '104432287034',
    projectId: 'trackify-f887d',
    authDomain: 'trackify-f887d.firebaseapp.com',
    storageBucket: 'trackify-f887d.appspot.com',
    measurementId: 'G-J07ZVFGRQD',
  );
}
